version: 0.2
env:
  variables:
    APP_NAME: "front-produto"
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo INSTALL DEPENDENCES
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo BUILD APLICATION
      - ng build --configuration=production
  post_build:
    commands:
      - echo INIT POST BUILD
      - cd dist/front-produto
      - ls -la
artifacts:
  files:
    - '**/*'
  base-directory: dist/front-produto*
  discard-paths: yes