version: 0.2
env:
  variables:
    APP_NAME: "front-produto"
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod --aot
  post_build:
    commands:
      - echo INIT POST BUILD
      - cd dist/$APP_NAME
      - ls -la
artifacts:
  files:
    - '**/*'
  base-directory: dist/$APP_NAME*
  discard-paths: yes